name: Upload coverage report

on:
  push:
    branches:
      - main
      - beta

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14.2]

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Generate coverage report
        run: yarn test:unit:coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage
